# Configuration file for network startup

# Network host IP address list and the number of Producer and Candidate on each physical machine
# The key string represents the host IP address 
# The first value represents the number of Producer nodes
# The second value represents the number of Candidate nodes

[network]
"192.168.9.43" = [4, 0]
